### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jdavidrcamacho** [j-faria/kima#1]
Weird thing is happening

I have two versions of kima, one before you made the more recent updates and another up to date.

The older version doesn't give me problems when I make ./run in the terminal. The new one gives me:

```
#Loaded 175 data points from file /home/joaocamacho/corot.txt
#Using 0 threads.
#Target compression factor between levels = 
Segmentation fault (core dumped)
```

Both use the same OPTIONS parameters.

**Comment by jdavidrcamacho** [comment]
Ok i think I've learned how to use gdb

```
(gdb) run
Starting program: /home/joaocamacho/GitHub/kima1/main 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
# Loaded 175 data points from file /home/joaocamacho/corot.txt
# Using 0 threads.
# Target compression factor between levels = 

Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245
245	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245
#1  0x0000000000407f29 in DNest4::Sampler<MyModel>::Sampler(unsigned int, double, DNest4::Options const&, bool) ()
#2  0x000000000040845c in DNest4::Sampler<MyModel> DNest4::setup<MyModel>(DNest4::CommandLineOptions const&) ()
#3  0x00000000004085ad in void DNest4::start<MyModel>(int, char**) ()
#4  0x0000000000403519 in main ()
(gdb) 
```

**Comment by j-faria** [comment]
Sorry just saw this now.
Can you test with the latest version?

It says it's using 0 threads which should never happen...

**Comment by jdavidrcamacho** [comment]
Don't worry
The new version doesn't give that problem and seems to work :D 
do you have any ideia why that was happening?
