### ISSUE TITLE
Travis buils of pykima

### ISSUE THREAD

**Issue by j-faria** [j-faria/kima#25]
The installation of `pykima` in Travis is broken...

```shell
$ python setup.py install
running install
running bdist_egg
running egg_info
creating pykima.egg-info
writing pykima.egg-info/PKG-INFO
writing top-level names to pykima.egg-info/top_level.txt
writing dependency_links to pykima.egg-info/dependency_links.txt
writing entry points to pykima.egg-info/entry_points.txt
writing manifest file 'pykima.egg-info/SOURCES.txt'
reading manifest file 'pykima.egg-info/SOURCES.txt'
writing manifest file 'pykima.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pykima.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pykima.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pykima.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pykima.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pykima.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pykima-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pykima-0.1-py2.7.egg
Copying pykima-0.1-py2.7.egg to /home/travis/miniconda/lib/python2.7/site-packages
Adding pykima 0.1 to easy-install.pth file
Installing kima-showresults script to /home/travis/miniconda/bin
Installed /home/travis/miniconda/lib/python2.7/site-packages/pykima-0.1-py2.7.egg
Processing dependencies for pykima==0.1
Finished processing dependencies for pykima==0.1

The command "python setup.py install" exited with 0.

$ python -c "import pykima"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pykima

The command "python -c "import pykima"" exited with 1.

$ kima-showresults -h
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/kima-showresults", line 9, in <module>
    load_entry_point('pykima==0.1', 'console_scripts', 'kima-showresults')()
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2202, in load
  File "/home/travis/miniconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2208, in resolve
ImportError: No module named pykima.showresults
The command "kima-showresults -h" exited with 1.
```

**Comment by j-faria** [comment]
Fixed... was simply missing the `__init__.py`... 🤦‍
